#!/usr/bin/env bash
set -euxo pipefail

# version="$1"
# image_path="$2"

b=/boot
esp=/efi
prefix=/EFI/ubuntu
e=$esp$prefix

options="rd.luks.name=41aec3cc-34dd-4745-ae5a-1df1b60c998d=LUKSROOT nohibernate loglevel=4 nvidia-drm.modeset=1"

tee $esp/loader/entries/ubuntu.conf <<EOF
title   Ubuntu
linux   $prefix/vmlinuz
initrd  $prefix/initrd.img
options ${options}
EOF
