#!/usr/bin/env bash
# copy updated kernel and initrd to efi system partition
set -euxo pipefail

b=/boot
esp=/efi
prefix=/EFI/ubuntu
e=$esp$prefix

mkdir -p $e

for kern in vmlinuz{,.old}; do
  if [[ $b/$kern -nt $e/$kern ]]; then
    cp -fv --preserve $b/$kern $e/$kern
  fi
done

for init in initrd.img{,.old}; do
  if [[ $b/$init -nt $e/$init ]]; then
    cp -fv --preserve=mode,ownership $b/$init $e/$init
  fi
done

options="root=/dev/mapper/LUKSROOT"

tee $esp/loader/entries/ubuntu.conf <<EOF
title   Ubuntu
linux  $prefix/vmlinuz
initrd $prefix/initrd.img
options ${options}
EOF

tee $esp/loader/entries/ubuntu-old.conf <<EOF
title   Ubuntu.old
linux  $prefix/vmlinuz.old
initrd $prefix/initrd.img.old
options ${options}
EOF
